import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import {Quote} from '@/components/Quote'
import {InputStartGame} from '@/components/inputStartGame';

import { Montserrat } from '@next/font/google';
import Layout from '@/components/Layout';
const montserrat = Montserrat({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Poznajmy się</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <main className={montserrat.className}>        
          <div className={styles.header}>
            <div className={styles.wrapper}>
              <h3>Poznajmy się.</h3>
              <p>QUIZ TOWARZYSKI</p>
            </div>
          <Image
                src="/open.webp"
                alt="Vercel Logo"
                width={180}
                height={196}                
              />          
          </div>
          <div className={styles.quoteWrapper}>          
          <Image
                src="/hero-glasses.webp"
                alt="Vercel Logo"
                width={180}
                height={196}                
              />          
            <Quote />
          </div>
          <InputStartGame />        
      </main>
      </Layout>
    </>
  )
}
